name: PR Close Preview

# 触发条件：PR关闭时
on:
  pull_request_target:
    types: [closed]

jobs:
  pr-close:
    runs-on: ubuntu-latest
    steps:
      - name: 删除 pr 目录
        run: |
          PR_DIR=prs/pr${{ github.event.number }}
          echo "删除 $PR_DIR"
          
          rm -rf $PR_DIR
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add -A
          git commit -m "🧹 remove preview $PR_DIR" || echo "Nothing to commit"
          
          git push
